'use client';
import { useEffect, useState } from 'react';
import { Calculator, FileText, History, LoaderCircle } from 'lucide-react';
import ToolLayout from '@/components/tool-layout';
import { readUsageHistory, saveUsageRecord, UsageRecord } from '@/lib/usage-history';

type Estimate={subtotalMaterial:number;vatAmount:number;laborFee:number;shippingFee:number;discountAmount:number;totalAmount:number};
const money=(value:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(value);

export default function QuotePage(){
 const [employeeCode,setEmployeeCode]=useState(''),[activeEmployee,setActiveEmployee]=useState(''),[customer,setCustomer]=useState(''),[project,setProject]=useState(''),[area,setArea]=useState(45),[effect,setEffect]=useState('Sơn hiệu ứng bê tông'),[labor,setLabor]=useState(2200000),[shipping,setShipping]=useState(300000),[discount,setDiscount]=useState(0),[result,setResult]=useState<Estimate|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<UsageRecord[]>([]);
 useEffect(()=>{if(activeEmployee)setHistory(readUsageHistory('quote',activeEmployee))},[activeEmployee]);
 const chooseEmployee=()=>{const code=employeeCode.trim().toUpperCase();if(code){setActiveEmployee(code);localStorage.setItem('akacons_employee_code',code)}};
 const calculate=async()=>{if(!activeEmployee||!customer||!project)return;setLoading(true);setError('');try{const response=await fetch('/api/estimates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({areaM2:Number(area),effectSystemId:effect,vatRate:10,laborFee:Number(labor),shippingFee:Number(shipping),discountAmount:Number(discount)})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Không thể lập báo giá');setResult(data.data);saveUsageRecord({kind:'quote',employeeCode:activeEmployee,title:project,status:'completed',details:{customer,area,effect,totalAmount:data.data.totalAmount}});setHistory(readUsageHistory('quote',activeEmployee))}catch(e){const message=e instanceof Error?e.message:'Lập báo giá thất bại';setError(message)}finally{setLoading(false)}};
 return <ToolLayout label="AKACONS ESTIMATE & QUOTE" title="Dự toán & Báo giá" description="Tính vật tư, chi phí thi công và lưu lịch sử báo giá theo từng mã nhân viên.">
  <div className="tool-shell"><div><section className="tool-card employee-gate"><h2>Mã nhân viên</h2><p className="subtitle">Mọi báo giá sẽ được ghi nhận theo mã này.</p><div className="employee-row"><input value={employeeCode} onChange={e=>setEmployeeCode(e.target.value.toUpperCase())} onKeyDown={e=>e.key==='Enter'&&chooseEmployee()} placeholder="Ví dụ: AKA-001"/><button onClick={chooseEmployee}>Xác nhận</button></div>{activeEmployee&&<small>Đang sử dụng: <b>{activeEmployee}</b></small>}</section>
  <section className="tool-card"><h2><Calculator size={20}/> Thông tin báo giá</h2><p className="subtitle">Nhập thông tin công trình để hệ thống tính chi phí.</p><div className="tool-fields"><Field label="Khách hàng"><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Tên khách hàng"/></Field><Field label="Công trình"><input value={project} onChange={e=>setProject(e.target.value)} placeholder="Tên công trình"/></Field><Field label="Diện tích (m²)"><input type="number" min="1" value={area} onChange={e=>setArea(Number(e.target.value))}/></Field><Field label="Hệ sơn"><select value={effect} onChange={e=>setEffect(e.target.value)}><option>Sơn hiệu ứng bê tông</option><option>Sơn vôi Limewash</option><option>Sơn hiệu ứng gỉ sét</option><option>Sơn hiệu ứng ngọc trai</option></select></Field><Field label="Nhân công"><input type="number" value={labor} onChange={e=>setLabor(Number(e.target.value))}/></Field><Field label="Vận chuyển"><input type="number" value={shipping} onChange={e=>setShipping(Number(e.target.value))}/></Field><Field label="Giảm giá"><input type="number" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></Field></div><button className="tool-action" disabled={!activeEmployee||!customer||!project||loading} onClick={calculate}>{loading?<LoaderCircle className="animate-spin"/>:<FileText/>}{loading?'Đang tính...':'Tính và lưu báo giá'}</button>{error&&<div className="error-message">{error}</div>}{result&&<div className="quote-result"><dl><dt>Vật tư</dt><dd>{money(result.subtotalMaterial)}</dd><dt>Nhân công</dt><dd>{money(result.laborFee)}</dd><dt>Vận chuyển</dt><dd>{money(result.shippingFee)}</dd><dt>VAT</dt><dd>{money(result.vatAmount)}</dd><dt>Giảm giá</dt><dd>-{money(result.discountAmount)}</dd></dl><div className="quote-total"><span>TỔNG BÁO GIÁ</span><strong>{money(result.totalAmount)}</strong></div></div>}</section></div><QuoteHistory records={history}/></div>
 </ToolLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="tool-field"><label>{label}</label>{children}</div>}
function QuoteHistory({records}:{records:UsageRecord[]}){return <aside className="tool-card history-card"><h2><History size={18}/> Lịch sử báo giá</h2><p className="subtitle">Theo mã nhân viên đang sử dụng.</p><div className="history-list">{records.length?records.map(r=><article className="history-item" key={r.id}><div><strong>{r.title}</strong><time>{new Date(r.createdAt).toLocaleString('vi-VN')}</time></div><p>{r.details.customer} · {r.details.area}m²<br/>{r.details.effect}<br/><b>{money(Number(r.details.totalAmount))}</b></p></article>):<div className="history-empty">Chưa có báo giá nào.</div>}</div></aside>}
